added the if conditions to simulate the workflow

diff --git a/.github/workflows/logic_test.yaml b/.github/workflows/logic_test.yaml
--- a/.github/workflows/logic_test.yaml
+++ b/.github/workflows/logic_test.yaml
@@ -7,10 +7,21 @@ on:
 jobs:
     logic-test:
         runs-on: ubuntu-latest
+        if: github.actor == 'karthikjetling03'
         steps:
-            - name: greet boss 
+            - name: greet boss
+              run: echo "Hey, Boss! How are you doing?"
+
+            - name: Simulate a crash
+              id: crash_step
               run: |
-                echo "${{github.ref_name}}"
-                echo "${{github.actor}}"
-                echo "${{github.event_name}}"
-                echo "${{github.repositoryUrl}}"
+                  echo "simulating a critical failure"
+                  exit 1
+
+            - name: Emergency Clean Up
+              if: failure()
+              run: echo "I am cleaning up the mess from the failed step"
+
+            - name: PR Only Message
+              if: github.event_name == 'pull_request'
+              run: echo "This message is for PR reviews only"
